const loginView=document.querySelector('#login-view'),dashboardView=document.querySelector('#dashboard-view'),content=document.querySelector('#content'),title=document.querySelector('#view-title');
const money=value=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format((Number(value)||0)/100);
const date=value=>value?new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(`${value.replace(' ','T')}Z`)):'—';
const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function api(path,options={}){const response=await fetch(`/api/${path}`,{credentials:'same-origin',...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok)throw Object.assign(new Error(data.error?.message||'Não foi possível concluir.'),{status:response.status});return data}
function table(headers,rows){return `<div class="panel"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.join(''):`<tr><td class="empty" colspan="${headers.length}">Nenhum registro encontrado.</td></tr>`}</tbody></table></div>`}
async function load(view){content.innerHTML='<p class="loading">Carregando…</p>';try{if(view==='overview'){title.textContent='Visão geral';const d=await api('admin/dashboard');content.innerHTML=`<div class="stats"><article class="stat"><span>Produtos ativos</span><strong>${d.stats.products}</strong></article><article class="stat"><span>Pedidos</span><strong>${d.stats.orders}</strong></article><article class="stat"><span>Clientes</span><strong>${d.stats.customers}</strong></article><article class="stat"><span>Vendas acumuladas</span><strong>${money(d.stats.revenue_cents)}</strong></article></div><div class="panel"><h2>Pedidos recentes</h2>${table(['Pedido','Cliente','Status','Total','Data'],d.recent_orders.map(o=>`<tr><td>${esc(o.order_number)}</td><td>${esc(o.customer_name)}</td><td><span class="status">${esc(o.status)}</span></td><td>${money(o.total_cents)}</td><td>${date(o.created_at)}</td></tr>`))}</div>`}if(view==='products'){title.textContent='Produtos';const d=await api('admin/products');content.innerHTML=table(['Produto','Categoria','SKU','Estoque','Preço','Situação'],d.products.map(p=>`<tr><td>${esc(p.name)}</td><td>${esc(p.category_name||'—')}</td><td>${esc(p.sku||'—')}</td><td>${p.stock}</td><td>${money(p.price_cents)}</td><td><span class="status">${p.active?'Ativo':'Inativo'}</span></td></tr>`))}if(view==='orders'){title.textContent='Pedidos';const d=await api('admin/orders');content.innerHTML=table(['Pedido','Cliente','Status','Entrega','Total','Data'],d.orders.map(o=>`<tr><td>${esc(o.order_number)}</td><td>${esc(o.customer_name)}<br><small>${esc(o.customer_email)}</small></td><td><span class="status">${esc(o.status)}</span></td><td>${esc(o.shipping_method)}</td><td>${money(o.total_cents)}</td><td>${date(o.created_at)}</td></tr>`))}if(view==='customers'){title.textContent='Clientes';const d=await api('admin/customers');content.innerHTML=table(['Cliente','Contato','Nascimento','Pedidos','Total gasto','Cadastro'],d.customers.map(c=>`<tr><td>${esc(c.name)}</td><td>${esc(c.email)}<br><small>${esc(c.phone||'')}</small></td><td>${esc(c.birth_date||'—')}</td><td>${c.order_count}</td><td>${money(c.total_spent_cents)}</td><td>${date(c.created_at)}</td></tr>`))}}catch(e){if(e.status===401||e.status===403)return showLogin();content.innerHTML=`<p class="message">${esc(e.message)}</p>`}}
function showDashboard(user){loginView.hidden=true;dashboardView.hidden=false;document.querySelector('#admin-name').textContent=user.name;load('overview')}
function showLogin(){dashboardView.hidden=true;loginView.hidden=false}
document.querySelector('#login-form').addEventListener('submit',async e=>{e.preventDefault();const message=document.querySelector('#login-message'),button=e.currentTarget.querySelector('button'),originalText=button.textContent;message.textContent='Validando acesso…';button.textContent='Entrando…';button.disabled=true;let opening=false;try{const body=Object.fromEntries(new FormData(e.currentTarget));const d=await api('auth/login',{method:'POST',body:JSON.stringify(body)});if(d.customer.role!=='admin'){await api('auth/logout',{method:'POST'});throw new Error('Este cadastro não possui permissão administrativa.')}opening=true;message.textContent='Acesso confirmado. Abrindo painel…';button.textContent='Abrindo painel…';window.location.replace('/admin?painel=1')}catch(err){message.textContent=err?.message||'Não foi possível entrar. Tente novamente.'}finally{if(!opening){button.textContent=originalText;button.disabled=false}}});
document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b===button));load(button.dataset.view)}));
document.querySelector('#logout').addEventListener('click',async()=>{await api('auth/logout',{method:'POST'}).catch(()=>{});showLogin()});
api('auth/me').then(d=>d.customer.role==='admin'?showDashboard(d.customer):showLogin()).catch(showLogin);
