const authSection=document.querySelector('#account-auth'),dashboard=document.querySelector('#account-dashboard'),message=document.querySelector('.account-message'),dashboardMessage=document.querySelector('.dashboard-message');
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const money=value=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format((Number(value)||0)/100);
async function api(path,options={}){const response=await fetch('/api/'+path,{credentials:'same-origin',...options,headers:{'Content-Type':'application/json',...(options.headers||{})}}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error?.message||'Não foi possível concluir.');return data}
function showMessage(text,error=false){const target=dashboard.hidden?message:dashboardMessage;target.textContent=text;target.classList.toggle('error',error)}
const authForms=['#account-login','#account-register','#account-forgot','#account-reset'];
const addressForm=document.querySelector('#address-form'),addressFields=addressForm.querySelector('.address-fields'),addressSummary=addressForm.querySelector('.address-summary');
function showSavedAddress(address){addressSummary.querySelector('p').textContent=[address.street,address.number,address.complement,address.neighborhood,[address.city,address.state].filter(Boolean).join(' - '),address.postal_code&&'CEP '+address.postal_code].filter(Boolean).join(', ');addressFields.hidden=true;addressSummary.hidden=false}
function showAuthForm(selector){authForms.forEach(id=>{document.querySelector(id).hidden=id!==selector});message.textContent='';message.classList.remove('error')}
document.querySelectorAll('[data-auth-tab]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-auth-tab]').forEach(item=>item.classList.toggle('active',item===button));showAuthForm(button.dataset.authTab==='login'?'#account-login':'#account-register')})
document.querySelector('#show-password-recovery').onclick=()=>showAuthForm('#account-forgot');
document.querySelectorAll('[data-back-to-login]').forEach(button=>button.onclick=()=>{history.replaceState({},'',location.pathname);showAuthForm('#account-login')});
const resetToken=new URLSearchParams(location.search).get('redefinir');
if(resetToken){document.querySelector('.account-tabs').hidden=true;showAuthForm('#account-reset')}
async function loadAccount(){const data=await api('account');authSection.hidden=true;dashboard.hidden=false;document.querySelector('#account-first-name').textContent=data.customer.name.split(/\s+/)[0];const profile=document.querySelector('#profile-form');for(const key of ['name','email','phone','birth_date'])profile.elements[key].value=data.customer[key]||'';if(data.address){for(const key of ['postal_code','street','number','complement','neighborhood','city','state'])addressForm.elements[key].value=data.address[key]||'';showSavedAddress(data.address)}else{addressFields.hidden=false;addressSummary.hidden=true}document.querySelector('#first-purchase-benefit').hidden=!data.first_purchase_eligible;document.querySelector('#loyalty-count').textContent=(Number(data.loyalty.purchase_count)||0)+' compras';document.querySelector('#account-orders').innerHTML=data.orders.length?data.orders.map(order=>'<article><div><strong>'+escapeHtml(order.order_number)+'</strong><small>'+new Date(order.created_at+'Z').toLocaleDateString('pt-BR')+'</small></div><span>'+escapeHtml(order.status)+'</span><b>'+money(order.total_cents)+'</b>'+(order.tracking_code?'<a href="rastreamento.html?codigo='+encodeURIComponent(order.tracking_code)+'">Rastrear →</a>':'')+'</article>').join(''):'<p>Você ainda não possui pedidos.</p>'}
document.querySelector('#account-login').onsubmit=async event=>{event.preventDefault();message.textContent='Entrando...';try{const data=Object.fromEntries(new FormData(event.currentTarget));await api('auth/login',{method:'POST',body:JSON.stringify(data)});await loadAccount()}catch(error){showMessage(error.message,true)}};
document.querySelector('#account-register').onsubmit=async event=>{event.preventDefault();message.textContent='Criando sua conta...';try{const data=Object.fromEntries(new FormData(event.currentTarget));await api('auth/register',{method:'POST',body:JSON.stringify(data)});await loadAccount()}catch(error){showMessage(error.message,true)}};
document.querySelector('#account-forgot').onsubmit=async event=>{event.preventDefault();const button=event.currentTarget.querySelector('[type="submit"]');button.disabled=true;message.textContent='Enviando...';try{const data=Object.fromEntries(new FormData(event.currentTarget));const result=await api('auth/password/forgot',{method:'POST',body:JSON.stringify(data)});showMessage(result.message)}catch(error){showMessage(error.message,true)}finally{button.disabled=false}};
document.querySelector('#account-reset').onsubmit=async event=>{event.preventDefault();const form=event.currentTarget,data=Object.fromEntries(new FormData(form));if(data.password!==data.password_confirmation){showMessage('As senhas precisam ser iguais.',true);return}const button=form.querySelector('[type="submit"]');button.disabled=true;message.textContent='Salvando...';try{const result=await api('auth/password/reset',{method:'POST',body:JSON.stringify({token:resetToken,password:data.password})});history.replaceState({},'',location.pathname);document.querySelector('.account-tabs').hidden=false;showAuthForm('#account-login');showMessage(result.message)}catch(error){showMessage(error.message,true)}finally{button.disabled=false}};
document.querySelector('#profile-form').onsubmit=async event=>{event.preventDefault();try{const data=Object.fromEntries(new FormData(event.currentTarget));await api('account',{method:'PUT',body:JSON.stringify(data)});showMessage('Dados atualizados com sucesso.')}catch(error){showMessage(error.message,true)}};
addressForm.onsubmit=async event=>{event.preventDefault();const form=event.currentTarget,button=form.querySelector('[type="submit"]'),status=form.querySelector('.address-message'),data=Object.fromEntries(new FormData(form));data.postal_code=String(data.postal_code||'').replace(/\D/g,'');data.state=String(data.state||'').trim().toUpperCase();button.disabled=true;button.textContent='Salvando...';status.classList.remove('error');status.textContent='Salvando endereço...';try{await api('account/address',{method:'PUT',body:JSON.stringify(data)});const saved=await api('account');if(saved.address){for(const key of ['postal_code','street','number','complement','neighborhood','city','state'])form.elements[key].value=saved.address[key]||'';showSavedAddress(saved.address)}}catch(error){status.textContent=error.message;status.classList.add('error')}finally{button.disabled=false;button.textContent='Salvar endereço'}};
addressSummary.querySelector('.account-address-edit').onclick=()=>{addressSummary.hidden=true;addressFields.hidden=false;addressForm.elements.postal_code.focus()};
const cepInput=document.querySelector('#address-form [name="postal_code"]');cepInput.onblur=async()=>{const cep=cepInput.value.replace(/\D/g,'');if(cep.length!==8)return;try{const data=await fetch('https://viacep.com.br/ws/'+cep+'/json/').then(response=>response.json());if(data.erro)return;const form=document.querySelector('#address-form');form.elements.street.value=data.logradouro||'';form.elements.neighborhood.value=data.bairro||'';form.elements.city.value=data.localidade||'';form.elements.state.value=data.uf||''}catch{}};
document.querySelector('#account-logout').onclick=async()=>{await api('auth/logout',{method:'POST'}).catch(()=>{});location.reload()};
if(!resetToken)api('auth/me').then(()=>loadAccount()).catch(()=>{});
