const authSection=document.querySelector('#account-auth'),dashboard=document.querySelector('#account-dashboard'),message=document.querySelector('.account-message'),dashboardMessage=document.querySelector('.dashboard-message');
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const money=value=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format((Number(value)||0)/100);
async function api(path,options={}){const response=await fetch('/api/'+path,{credentials:'same-origin',...options,headers:{'Content-Type':'application/json',...(options.headers||{})}}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error?.message||'Não foi possível concluir.');return data}
function showMessage(text,error=false){const target=dashboard.hidden?message:dashboardMessage;target.textContent=text;target.classList.toggle('error',error)}
document.querySelectorAll('[data-auth-tab]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-auth-tab]').forEach(item=>item.classList.toggle('active',item===button));document.querySelector('#account-login').hidden=button.dataset.authTab!=='login';document.querySelector('#account-register').hidden=button.dataset.authTab!=='register';message.textContent=''})
async function loadAccount(){const data=await api('account');authSection.hidden=true;dashboard.hidden=false;document.querySelector('#account-first-name').textContent=data.customer.name.split(/\s+/)[0];const profile=document.querySelector('#profile-form');for(const key of ['name','email','phone','birth_date'])profile.elements[key].value=data.customer[key]||'';const address=document.querySelector('#address-form');if(data.address)for(const key of ['postal_code','street','number','complement','neighborhood','city','state'])address.elements[key].value=data.address[key]||'';document.querySelector('#first-purchase-benefit').hidden=!data.first_purchase_eligible;document.querySelector('#loyalty-count').textContent=(Number(data.loyalty.purchase_count)||0)+' compras';document.querySelector('#account-orders').innerHTML=data.orders.length?data.orders.map(order=>'<article><div><strong>'+escapeHtml(order.order_number)+'</strong><small>'+new Date(order.created_at+'Z').toLocaleDateString('pt-BR')+'</small></div><span>'+escapeHtml(order.status)+'</span><b>'+money(order.total_cents)+'</b>'+(order.tracking_code?'<a href="rastreamento.html?codigo='+encodeURIComponent(order.tracking_code)+'">Rastrear →</a>':'')+'</article>').join(''):'<p>Você ainda não possui pedidos.</p>'}
document.querySelector('#account-login').onsubmit=async event=>{event.preventDefault();message.textContent='Entrando...';try{const data=Object.fromEntries(new FormData(event.currentTarget));await api('auth/login',{method:'POST',body:JSON.stringify(data)});await loadAccount()}catch(error){showMessage(error.message,true)}};
document.querySelector('#account-register').onsubmit=async event=>{event.preventDefault();message.textContent='Criando sua conta...';try{const data=Object.fromEntries(new FormData(event.currentTarget));await api('auth/register',{method:'POST',body:JSON.stringify(data)});await loadAccount()}catch(error){showMessage(error.message,true)}};
document.querySelector('#profile-form').onsubmit=async event=>{event.preventDefault();try{const data=Object.fromEntries(new FormData(event.currentTarget));await api('account',{method:'PUT',body:JSON.stringify(data)});showMessage('Dados atualizados com sucesso.')}catch(error){showMessage(error.message,true)}};
document.querySelector('#address-form').onsubmit=async event=>{event.preventDefault();try{const data=Object.fromEntries(new FormData(event.currentTarget));await api('account/address',{method:'PUT',body:JSON.stringify(data)});showMessage('Endereço salvo com sucesso.')}catch(error){showMessage(error.message,true)}};
const cepInput=document.querySelector('#address-form [name="postal_code"]');cepInput.onblur=async()=>{const cep=cepInput.value.replace(/\D/g,'');if(cep.length!==8)return;try{const data=await fetch('https://viacep.com.br/ws/'+cep+'/json/').then(response=>response.json());if(data.erro)return;const form=document.querySelector('#address-form');form.elements.street.value=data.logradouro||'';form.elements.neighborhood.value=data.bairro||'';form.elements.city.value=data.localidade||'';form.elements.state.value=data.uf||''}catch{}};
document.querySelector('#account-logout').onclick=async()=>{await api('auth/logout',{method:'POST'}).catch(()=>{});location.reload()};
api('auth/me').then(()=>loadAccount()).catch(()=>{});