(function(){
  const title=document.querySelector('#payment-title'),text=document.querySelector('#payment-text'),statusEl=document.querySelector('#payment-status'),orderEl=document.querySelector('#payment-order');
  const params=new URLSearchParams(location.search),order=params.get('pedido')||sessionStorage.getItem('elegance-last-order')||'',returnStatus=params.get('status');
  orderEl.textContent=order||'—';
  const labels={paid:['Pagamento confirmado!','Seu pedido foi recebido e já aparece no painel da Elegance.'],payment_review:['Pagamento recebido — pedido em análise','A Elegance precisa conferir a disponibilidade dos itens antes de confirmar a entrega. Entre em contato com a loja informando o número do pedido.'],pending_payment:['Pagamento em processamento','Estamos aguardando a confirmação do Mercado Pago.'],cancelled:['Pagamento não concluído','Você pode voltar à sacola e tentar novamente.'],refunded:['Pagamento devolvido','O pagamento foi estornado pelo Mercado Pago.']};
  async function check(attempt=0){
    if(!order){title.textContent='Pedido não localizado';text.textContent='Volte à loja e confira sua sacola.';return}
    try{const response=await fetch(`/api/payments/status?pedido=${encodeURIComponent(order)}`),result=await response.json();if([401,403,404].includes(response.status)){title.textContent='Consulte seu pedido com segurança';text.textContent='Use o mesmo navegador da compra ou entre em Minha conta para consultar este pedido.';const link=document.createElement('a');link.href='/conta';link.textContent='Entrar em Minha conta';text.append(document.createElement('br'),link);statusEl.textContent='Acesso protegido';return}if(!response.ok)throw new Error();const status=result.order.status,[heading,copy]=labels[status]||labels.pending_payment;title.textContent=heading;text.textContent=copy;statusEl.textContent=heading;statusEl.dataset.status=status;if(status==='paid'){localStorage.removeItem('elegance-cart');return}if(attempt<5&&returnStatus==='success')setTimeout(()=>check(attempt+1),3000)}catch{title.textContent='Consultando pagamento';text.textContent='A confirmação pode levar alguns instantes. Atualize esta página em breve.'}}
  check();
})();
