const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const {DatabaseSync}=require('node:sqlite');
const db=new DatabaseSync(':memory:');
db.exec("CREATE TABLE customers(id INTEGER PRIMARY KEY); CREATE TABLE orders(id INTEGER PRIMARY KEY); CREATE TABLE gift_cards(id INTEGER PRIMARY KEY,code_hash TEXT UNIQUE,purchaser_customer_id INTEGER,recipient_name TEXT,recipient_phone TEXT,message TEXT,initial_cents INTEGER,balance_cents INTEGER,status TEXT DEFAULT 'pending_payment',expires_at TEXT)");
db.exec(fs.readFileSync('migrations/0011_gift_card_checkout.sql','utf8'));
db.exec("INSERT INTO customers VALUES(1); INSERT INTO orders(id) VALUES(1),(2),(3); INSERT INTO gift_cards(id,code_hash,initial_cents,balance_cents,status) VALUES(1,'hash',20000,0,'pending_payment'); INSERT INTO gift_card_sales(id,gift_card_id,customer_id,amount_cents,request_key) VALUES('GFT-test',1,1,20000,'key')");
const balance=()=>db.prepare('SELECT balance_cents FROM gift_cards WHERE id=1').get().balance_cents;
const DB={prepare(sql){return{bind(...args){return{async first(){return db.prepare(sql).get(...args)||null},async all(){return{results:db.prepare(sql).all(...args)}},sql,args}}}},async batch(items){db.exec('BEGIN');try{for(const item of items)db.prepare(item.sql).run(...item.args);db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');throw e}}};
let source=require('node:module').stripTypeScriptTypes(fs.readFileSync('functions/_lib/gift-cards.ts','utf8')).replace(/^import .*;$/gm,'').replaceAll('export async function','async function');
source+='\nglobalThis.sync=syncGiftPayment;';
const context={};vm.createContext(context);vm.runInContext(source,context);
(async()=>{
 await assert.rejects(context.sync({DB},{id:1,status:'approved',transaction_amount:100,external_reference:'GFT-test'}));
 assert.equal(balance(),0);
 await context.sync({DB},{id:1,status:'approved',transaction_amount:200,external_reference:'GFT-test'});
 assert.equal(balance(),20000);
 db.exec("INSERT INTO gift_card_uses(order_id,gift_card_id,amount_cents) VALUES(1,1,5000)");
 assert.equal(balance(),15000);
 await context.sync({DB},{id:1,status:'approved',transaction_amount:200,external_reference:'GFT-test'});
 assert.equal(balance(),15000);
 assert.throws(()=>db.exec("INSERT INTO gift_card_uses(order_id,gift_card_id,amount_cents) VALUES(2,1,16000)"),/GIFT_BALANCE_UNAVAILABLE/);
 assert.equal(balance(),15000);
 db.exec("UPDATE gift_card_uses SET status='spent' WHERE order_id=1");assert.equal(balance(),15000);
 db.exec("INSERT INTO gift_card_uses(order_id,gift_card_id,amount_cents) VALUES(2,1,15000)");assert.equal(balance(),0);
 db.exec("UPDATE gift_card_uses SET status='released' WHERE order_id=2");assert.equal(balance(),15000);
 db.exec("UPDATE gift_card_uses SET status='released' WHERE order_id=2");assert.equal(balance(),15000);
 db.exec("UPDATE gift_card_uses SET status='released' WHERE order_id=1");assert.equal(balance(),20000);
 await context.sync({DB},{id:1,status:'refunded',transaction_amount:200,external_reference:'GFT-test'});
 assert.throws(()=>db.exec("INSERT INTO gift_card_uses(order_id,gift_card_id,amount_cents) VALUES(3,1,5000)"),/GIFT_BALANCE_UNAVAILABLE/);
 await context.sync({DB},{id:1,status:'approved',transaction_amount:200,external_reference:'GFT-test'});
 assert.equal(db.prepare('SELECT status FROM gift_cards WHERE id=1').get().status,'refunded');
 console.log('PASS: verified amount, activation, duplicate notification, partial/full balance, overspend rejection, refund idempotency, refunded card remains blocked');
})().catch(error=>{console.error(error);process.exit(1)});
