/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/stock-scheduler/wrangler.jsonc --include-runtime=false --env-interface=StockSchedulerEnv workers/stock-scheduler/worker-configuration.d.ts` (hash: 83815e062a674cc9c3ada139577680de)
interface __BaseEnv_StockSchedulerEnv {
	DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_StockSchedulerEnv {}
}
interface StockSchedulerEnv extends __BaseEnv_StockSchedulerEnv {}
